export const emptyTiles = [
  { id: 1, frontColor: 'lightgrey', backColor: '', isGuessed: false },
  { id: 2, frontColor: 'lightgrey', backColor: '', isGuessed: false },
  { id: 3, frontColor: 'lightgrey', backColor: '', isGuessed: false },
  { id: 4, frontColor: 'lightgrey', backColor: '', isGuessed: false },
  { id: 5, frontColor: 'lightgrey', backColor: '', isGuessed: false },
  { id: 6, frontColor: 'lightgrey', backColor: '', isGuessed: false },
  { id: 7, frontColor: 'lightgrey', backColor: '', isGuessed: false },
  { id: 8, frontColor: 'lightgrey', backColor: '', isGuessed: false },
  { id: 9, frontColor: 'lightgrey', backColor: '', isGuessed: false },
  { id: 10, frontColor: 'lightgrey', backColor: '', isGuessed: false },
  { id: 11, frontColor: 'lightgrey', backColor: '', isGuessed: false },
  { id: 12, frontColor: 'lightgrey', backColor: '', isGuessed: false },
  { id: 13, frontColor: 'lightgrey', backColor: '', isGuessed: false },
  { id: 14, frontColor: 'lightgrey', backColor: '', isGuessed: false },
  { id: 15, frontColor: 'lightgrey', backColor: '', isGuessed: false },
  { id: 16, frontColor: 'lightgrey', backColor: '', isGuessed: false },
];
